# Demo services and sub-services full content (from design/src/data).
# Keys match Django model/related names: benefits (text), required_documents (text), process_steps, etc.

DEMO_SERVICES = [
    {
        "slug": "visa",
        "title": "Visa Services",
        "short_title": "Visa",
        "tagline": "Complete UAE Visa Solutions for Individuals & Businesses",
        "description": "Comprehensive visa processing services for employment, investor, family, and all other UAE visa categories. We handle the entire process from application to approval with guaranteed results.",
        "long_description": "Comprehensive visa processing services for employment, investor, family, and all other UAE visa categories.",
        "starting_price": "SAR 500",
        "timeline": "5-14 working days (depending on visa type)",
        "offer_badge": "20% Off Visit Visas",
        "category": "general",
        "benefits": [
            "Fast-track processing with priority handling",
            "100% approval rate guarantee",
            "Complete document preparation assistance",
            "Real-time status tracking",
            "Expert guidance throughout the process",
            "Competitive pricing with no hidden fees",
            "Multi-language support available",
            "Door-to-door document collection",
        ],
        "required_documents": [
            "Valid passport (minimum 6 months validity)",
            "Passport-size photographs (white background)",
            "Emirates ID (for renewals/status change)",
            "Employment contract (for work visas)",
            "Educational certificates (attested)",
            "Medical fitness certificate",
            "Proof of relationship (for family visas)",
            "Bank statements (for investor visas)",
        ],
        "process_steps": [
            {"step_number": 1, "title": "Initial Consultation", "description": "Free consultation to understand your visa requirements and eligibility", "timeline": "Same Day"},
            {"step_number": 2, "title": "Document Collection", "description": "We collect and verify all required documents", "timeline": "1-2 Days"},
            {"step_number": 3, "title": "Application Submission", "description": "Submit application to relevant authorities", "timeline": "1 Day"},
            {"step_number": 4, "title": "Processing & Follow-up", "description": "Track progress and handle any queries", "timeline": "3-7 Days"},
            {"step_number": 5, "title": "Medical & Emirates ID", "description": "Coordinate medical test and Emirates ID application", "timeline": "2-3 Days"},
            {"step_number": 6, "title": "Visa Stamping", "description": "Final visa stamping and delivery", "timeline": "1-2 Days"},
        ],
        "deliverables": [
            "Entry permit / Visa approval",
            "Medical fitness certificate",
            "Emirates ID application",
            "Visa stamping on passport",
            "Complete documentation folder",
        ],
        "price_tiers": [
            {"name": "Basic", "price": "SAR 2,500", "description": "Standard visa processing", "features": ["Document preparation", "Application submission", "Basic follow-up", "Email support"], "is_popular": False},
            {"name": "Professional", "price": "SAR 4,000", "description": "Priority processing with extras", "features": ["Everything in Basic", "Priority processing", "Medical coordination", "Emirates ID assistance", "WhatsApp support"], "is_popular": True},
            {"name": "Premium", "price": "SAR 6,500", "description": "VIP end-to-end service", "features": ["Everything in Professional", "Door-to-door service", "Dedicated account manager", "Express processing", "24/7 support"], "is_popular": False},
        ],
        "faqs": [
            {"question": "How long does visa processing take?", "answer": "Processing time varies by visa type. Visit visas take 2-3 days, employment visas 7-10 days, and family visas 10-14 days. We offer express processing for urgent cases."},
            {"question": "What documents are required for a family visa?", "answer": "You need a valid passport, sponsor's visa copy, Emirates ID, salary certificate (minimum SAR 4,000 for spouse), marriage certificate (attested), and tenancy contract."},
            {"question": "Can I change my visa status inside UAE?", "answer": "Yes, status change is possible for most visa types. You can change from visit to employment or investor visa without leaving the country."},
            {"question": "What is the validity period of UAE visas?", "answer": "Employment and family visas are typically valid for 2-3 years. Investor visas can be valid for 5-10 years. Visit visas range from 30-90 days."},
            {"question": "Do you guarantee visa approval?", "answer": "We have a 99% approval rate and guarantee to refund our service fee if the visa is rejected due to our error. However, final approval depends on immigration authorities."},
        ],
        "target_users": ["Individuals", "Employees", "Employers", "Investors", "Families"],
        "meta_title": "UAE Visa Services | Employment, Family & Investor Visa Processing",
        "meta_description": "Professional UAE visa services including employment visa, family visa, investor visa, and Golden Visa. Fast processing, 99% approval rate. Get a free consultation today.",
        "meta_keywords": "UAE visa, Dubai visa, employment visa UAE, family visa Dubai, investor visa, Golden Visa UAE",
        "sub_services": [
            {"slug": "employment-visa", "title": "Employment Visa", "description": "Work visa for employees sponsored by UAE companies", "price": "From SAR 2,500", "timeline": "7-10 days"},
            {"slug": "visit-visa", "title": "Visit Visa", "description": "Short and long-term tourist visas for UAE entry", "price": "From SAR 500", "timeline": "2-3 days"},
            {"slug": "family-visa", "title": "Family Visa", "description": "Residence visa for spouse, children, and parents", "price": "From SAR 3,000", "timeline": "10-14 days"},
            {"slug": "investor-visa", "title": "Investor Visa", "description": "Residence visa for business owners and investors", "price": "From SAR 5,000", "timeline": "14-21 days"},
            {"slug": "partner-visa", "title": "Partner Visa", "description": "Visa for business partners and stakeholders", "price": "From SAR 4,000", "timeline": "10-14 days"},
            {"slug": "visa-renewal", "title": "Visa Renewal", "description": "Extend your existing UAE residence visa", "price": "From SAR 2,000", "timeline": "5-7 days"},
            {"slug": "visa-cancellation", "title": "Visa Cancellation", "description": "Proper visa cancellation and exit procedures", "price": "From SAR 500", "timeline": "1-3 days"},
            {"slug": "status-change", "title": "Status Change", "description": "Change visa status inside or outside UAE", "price": "From SAR 1,500", "timeline": "3-5 days"},
        ],
    },
]

DEMO_SUB_SERVICES_FULL = [
    {
        "parent_slug": "visa",
        "slug": "employment-visa",
        "title": "Employment Visa",
        "tagline": "Start Your Career Journey in the UAE",
        "description": "Work visa for employees sponsored by UAE companies with full residency benefits.",
        "long_description": "The UAE Employment Visa is your gateway to working legally in the Emirates. This visa allows foreign nationals to work for UAE-based companies under a valid employment contract. Our expert team handles the entire process from entry permit to final visa stamping, ensuring a smooth transition to your new career in the UAE.",
        "starting_price": "SAR 2,500",
        "timeline": "7-10 working days",
        "offer_badge": "Express Available",
        "benefits": [
            "Legal right to work and reside in UAE",
            "Access to UAE banking and financial services",
            "Ability to sponsor family members",
            "Emirates ID for government services",
            "Access to UAE healthcare system",
            "Multiple re-entry during validity",
            "Path to long-term residency",
            "No income tax on salary",
        ],
        "required_documents": [
            "Valid passport (minimum 6 months validity)",
            "Passport-size photographs (white background)",
            "Attested educational certificates",
            "Employment contract (signed)",
            "Company trade license copy",
            "Establishment card",
            "Health insurance",
            "Medical fitness test results",
        ],
        "process_steps": [
            {"step_number": 1, "title": "Job Offer & Contract", "description": "Receive and sign employment offer from UAE company", "timeline": "Varies", "documents": ["Employment contract", "Offer letter"]},
            {"step_number": 2, "title": "Entry Permit Application", "description": "Employer applies for your entry permit through immigration", "timeline": "2-3 Days", "documents": ["Passport copy", "Photographs", "Job offer"]},
            {"step_number": 3, "title": "Entry to UAE", "description": "Travel to UAE using the entry permit (valid for 60 days)", "timeline": "1 Day"},
            {"step_number": 4, "title": "Medical Fitness Test", "description": "Complete medical examination at approved health center", "timeline": "1-2 Days", "documents": ["Passport", "Entry permit"]},
            {"step_number": 5, "title": "Emirates ID Biometrics", "description": "Provide biometrics at authorized typing center", "timeline": "1 Day", "documents": ["Passport", "Medical results"]},
            {"step_number": 6, "title": "Visa Stamping", "description": "Final visa stamp on passport confirming residency", "timeline": "2-3 Days", "documents": ["All previous documents"]},
        ],
        "deliverables": [
            "Entry permit (electronic)",
            "Medical fitness certificate",
            "Emirates ID application",
            "Residence visa stamp on passport",
            "Labor card",
            "Welcome kit with UAE essentials guide",
        ],
        "price_tiers": [
            {"name": "Standard", "price": "SAR 2,500", "description": "Basic employment visa processing", "features": ["Entry permit application", "Basic document guidance", "Medical test booking", "Visa stamping", "Email support"], "is_popular": False},
            {"name": "Express", "price": "SAR 4,000", "description": "Fast-track processing", "features": ["Everything in Standard", "Priority processing", "Emirates ID expedited", "Airport pickup", "WhatsApp support", "Document collection"], "is_popular": True},
            {"name": "VIP", "price": "SAR 6,500", "description": "Complete concierge service", "features": ["Everything in Express", "Dedicated case manager", "Same-day medical booking", "Door-to-door service", "24/7 support", "Family visa assistance"], "is_popular": False},
        ],
        "eligibility": [
            "Valid job offer from UAE-registered company",
            "Age between 18-65 years",
            "No criminal record",
            "Medically fit",
            "Educational qualifications matching job role",
            "Company must have valid establishment card",
        ],
        "faqs": [
            {"question": "How long is an employment visa valid?", "answer": "Employment visas are typically valid for 2-3 years, depending on the emirate and employer. The visa can be renewed upon expiry."},
            {"question": "Can I change employers on an employment visa?", "answer": "Yes, you can change employers. The process requires canceling your current visa and obtaining a new one from the new employer. No-objection certificates may be required."},
            {"question": "What happens if I lose my job?", "answer": "You have a 30-day grace period after visa cancellation to find a new job, change your visa status, or leave the UAE. This can be extended in certain cases."},
            {"question": "Can my family join me on an employment visa?", "answer": "Yes, once your employment visa is stamped, you can sponsor your spouse, children, and parents (with certain conditions) for family residence visas."},
        ],
        "meta_title": "UAE Employment Visa | Work Visa Dubai | Fast Processing",
        "meta_description": "Get your UAE employment visa processed in 7-10 days. Expert handling of work permits, labor cards, and residency visas. 99% approval rate. Free consultation.",
        "meta_keywords": "UAE employment visa, work visa Dubai, UAE work permit, Dubai job visa, labor card UAE",
    },
    {
        "parent_slug": "visa",
        "slug": "visit-visa",
        "title": "Visit Visa",
        "tagline": "Explore the Emirates with Ease",
        "description": "Short and long-term tourist visas for UAE entry with flexible durations.",
        "long_description": "Whether you're visiting for tourism, business meetings, or visiting family, our UAE Visit Visa service provides hassle-free entry to the Emirates. We offer 30-day, 60-day, and 90-day options with single or multiple entry permits, processed within 24-48 hours.",
        "starting_price": "SAR 500",
        "timeline": "2-3 working days",
        "offer_badge": "20% Off 60-Day Visa",
        "benefits": [
            "Quick processing (24-48 hours)",
            "Multiple duration options (30/60/90 days)",
            "Single and multiple entry options",
            "No sponsor required for many nationalities",
            "Extension possible inside UAE",
            "Valid for all UAE emirates",
            "Business and tourist purposes",
            "No deposit required",
        ],
        "required_documents": [
            "Valid passport (minimum 6 months validity)",
            "Passport-size photograph",
            "Flight itinerary",
            "Hotel booking (if applicable)",
            "Travel insurance (recommended)",
            "Proof of funds (for some nationalities)",
        ],
        "process_steps": [
            {"step_number": 1, "title": "Application Submission", "description": "Submit passport copy and required documents", "timeline": "Same Day"},
            {"step_number": 2, "title": "Processing", "description": "Immigration reviews and processes the application", "timeline": "24-48 Hours"},
            {"step_number": 3, "title": "Visa Approval", "description": "Receive electronic visa via email", "timeline": "Same Day"},
            {"step_number": 4, "title": "Travel to UAE", "description": "Present visa at UAE immigration upon arrival", "timeline": "As per travel date"},
        ],
        "deliverables": [
            "Electronic visa approval (PDF)",
            "Visa reference number",
            "Entry instructions",
            "24/7 travel support contact",
        ],
        "price_tiers": [
            {"name": "30-Day Single Entry", "price": "SAR 500", "description": "Short stay visa", "features": ["30 days validity", "Single entry", "Tourist/Business", "48-hour processing"], "is_popular": False},
            {"name": "60-Day Multi Entry", "price": "SAR 1,200", "description": "Extended stay with flexibility", "features": ["60 days validity", "Multiple entries", "Extendable", "Priority processing"], "is_popular": True},
            {"name": "90-Day Multi Entry", "price": "SAR 1,800", "description": "Long-term visit", "features": ["90 days validity", "Multiple entries", "Extendable", "VIP processing", "Airport assistance"], "is_popular": False},
        ],
        "faqs": [
            {"question": "Can I extend my visit visa inside UAE?", "answer": "Yes, visit visas can be extended twice for 30 days each, for a maximum stay of 90 days. Extension must be applied before visa expiry."},
            {"question": "Can I work on a visit visa?", "answer": "No, visit visas do not permit employment. You need an employment visa to work legally in the UAE."},
        ],
        "meta_title": "UAE Visit Visa | Tourist Visa Dubai | 24-Hour Processing",
        "meta_description": "Apply for UAE tourist visa online. 30, 60, 90-day options available. Fast 24-48 hour processing. No hidden fees. Apply now!",
        "meta_keywords": "UAE visit visa, Dubai tourist visa, UAE visa online, visit visa Dubai",
    },
]
